name: Java ci/cd with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: init with Gradle
      uses: gradle/gradle-build-action@v2
      
    - run: gradle init

    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5.1
        arguments: build

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gsample01 .

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: docker hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gsample01

  deploy:
    needs: build
    name: deploy
    runs-on: [self-hosted, label-1]
    steps:
    - name: login dockerhub
      uses: dokcer/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker run
      run : |
        docker stop gs01 && docker rm gs 01 && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/gsample01:latest
        docker run -d --name gs01 -p 50001:50001 --restart always ${{ secrets.DOCKERHUB_USERNAME }}/gsample01:latest
      
